name: Heroku

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import GPG Key
        run: |
          if [ ! -z ${{ secrets.GPG_KEY }} ]; then
            while IFS= read -r line; do
              echo "$line" >> gpg.asc
            done <<< "${{ secrets.GPG_KEY }}"
            gpg_str=$(gpg --list-packets gpg.asc | grep "^:user ID packet" | sed -r "s/^.{18}//" | sed "s/.$//")
            echo $gpg_str
            email=`echo $gpg_str | grep -Po "(?<=\<).*?(?=\>)"`
            name=`echo $gpg_str | sed "s/.(.*//"`
            signing_key=$(gpg --list-packets gpg.asc | grep -m 1 "*keyid:" | sed -r "s/^.{7}//")
            git config --global user.email "$email"
            git config --global user.name "$name"
            git config --global user.signingkey "$signing_key"
            gpg --import gpg.asc
          else
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
          fi
      - name: Push to Heroku
        id: push_to_heroku
        run: |
          echo ${{ github.repository }}
          mkdir ./release
          git clone https://github.com/anasty17/mirror-leech-telegram-bot.git hrk
          cd hrk
          if [ ! -z ${{ secrets.GPG_KEY }} ]; then
            git commit -S -m "Automated release $tag"
          else
            git commit -m "Automated release $tag"
          fi
          git push
